var rawOptions = [
    {
        "fundId":1003,
        "fundName":"Фонд МДТЗК",
        "statusName":"В продаже",
        "type":"mdtzk"
    },
    {
        "fundId":1521,
        "fundName":"Неиспользуемые места",
        "statusName":"Не использовать",
        "type":"mdtzk"
    },
    {
        "fundId":1531,
        "fundName":"Фонд театра",
        "statusName":"",
        "type":"mdtzk"
    },
    {
        "fundId":3939,
        "fundName":"Общее поле",
        "statusName":"",
        "type":"custom"
    },
    {
        "fundId":407490,
        "fundName":"Абонемент",
        "statusName":"Абонементы",
        "type":"mdtzk"
    },
    {
        "fundId":407491,
        "fundName":"МТС Привилегии",
        "statusName":"МТС premium",
        "type":"mdtzk"
    },
    {
        "fundId":407492,
        "fundName":"МТС привилегии (НЕРЕАЛЬНЫЙ)",
        "statusName":"",
        "type":"custom"
    },
    {
        "fundId":407496,
        "fundName":"Поклонникам",
        "statusName":"",
        "type":"special"
    },
    {
        "fundId":407497,
        "fundName":"Спонсорам",
        "statusName":"",
        "type":"special"
    },
    {
        "fundId":407498,
        "fundName":"Друзьям",
        "statusName":"",
        "type":"special"
    },
    {
        "fundId":407509,
        "fundName":"Меньшик",
        "statusName":"",
        "type":"custom"
    },
    {
        "fundId":407521,
        "fundName":"Меньшик2",
        "statusName":"",
        "type":"custom"
    },
    {
        "fundId":407522,
        "fundName":"",
        "statusName":"",
        "type":"custom"
    },
    {
        "fundId":407526,
        "fundName":"Test Test",
        "statusName":"",
        "type":"custom"
    },
    {
        "fundId":407528,
        "fundName":"Test1",
        "statusName":"",
        "type":"custom"
    },
    {
        "fundId":407546,
        "fundName":"Test2",
        "statusName":"",
        "type":"custom"
    },
    {
        "fundId":407547,
        "fundName":"Test3",
        "statusName":"",
        "type":"custom"
    },
    {
        "fundId":407566,
        "fundName":"Test123",
        "statusName":"",
        "type":"custom"
    },
    {
        "fundId":407568,
        "fundName":"Test1234",
        "statusName":"",
        "type":"custom"
    },
    {
        "fundId":407581,
        "fundName":"TestTest",
        "statusName":"",
        "type":"custom"
    },
    {
        "fundId":407582,
        "fundName":"TestTwo",
        "statusName":"",
        "type":"custom"
    },
    {
        "fundId":407586,
        "fundName":"TestQwerty",
        "statusName":"",
        "type":"custom"
    },
    {
        "fundId":407588,
        "fundName":"Test12345",
        "statusName":"",
        "type":"custom"
    },
    {
        "fundId":407589,
        "fundName":"Check",
        "statusName":"",
        "type":"custom"
    },
    {
        "fundId":407610,
        "fundName":"Test345",
        "statusName":"",
        "type":"custom"
    },
    {
        "fundId":407614,
        "fundName":"TestFinish",
        "statusName":"",
        "type":"custom"
    },
    {
        "fundId":407638,
        "fundName":"Testqwe",
        "statusName":"",
        "type":"custom"
    },
    {
        "fundId":407639,
        "fundName":"Привет",
        "statusName":"",
        "type":"custom"
    },
    {
        "fundId":407640,
        "fundName":"new_funnnd",
        "statusName":"",
        "type":"custom"
    },
    {
        "fundId":407643,
        "fundName":"Test4",
        "statusName":"",
        "type":"custom"
    },
    {
        "fundId":407644,
        "fundName":"тестСтатус",
        "statusName":"",
        "type":"custom"
    },
    {
        "fundId":407645,
        "fundName":"тестСтатус1",
        "statusName":"",
        "type":"custom"
    },
    {
        "fundId":407646,
        "fundName":"Чее",
        "statusName":"",
        "type":"custom"
    },
    {
        "fundId":407647,
        "fundName":"Сап двощ",
        "statusName":"",
        "type":"custom"
    },
    {
        "fundId":407648,
        "fundName":"Финтифлюшка",
        "statusName":"",
        "type":"custom"
    },
    {
        "fundId":407649,
        "fundName":"Флюгегехаймен",
        "statusName":"",
        "type":"custom"
    },
    {
        "fundId":407650,
        "fundName":"Давид потестил",
        "statusName":"",
        "type":"custom"
    },
    {
        "fundId":407496,
        "fundName":"Поклонникам",
        "statusName":"Тест",
        "type":"special"
    },
    {
        "fundId":407498,
        "fundName":"Друзьям",
        "statusName":"nhjhgjghj",
        "type":"special"
    },
    {
        "fundId":407496,
        "fundName":"Поклонникам",
        "statusName":"132",
        "type":"special"
    },
    {
        "fundId":407496,
        "fundName":"Поклонникам",
        "statusName":"Меньшик спецпродажа",
        "type":"special"
    },
    {
        "fundId":407496,
        "fundName":"Поклонникам",
        "statusName":"три пробела",
        "type":"special"
    },
    {
        "fundId":407497,
        "fundName":"Спонсорам",
        "statusName":"03.12.2021",
        "type":"special"
    },
    {
        "fundId":407497,
        "fundName":"Спонсорам",
        "statusName":"2",
        "type":"special"
    },
    {
        "fundId":407497,
        "fundName":"Спонсорам",
        "statusName":"1",
        "type":"special"
    },
    {
        "fundId":407496,
        "fundName":"Поклонникам",
        "statusName":"knnlkok;l",
        "type":"special"
    },
    {
        "fundId":407496,
        "fundName":"Поклонникам",
        "statusName":"spec(1.10.21)",
        "type":"special"
    },
    {
        "fundId":407497,
        "fundName":"Спонсорам",
        "statusName":"expert(30.09 for sponsors)",
        "type":"special"
    },
    {
        "fundId":407498,
        "fundName":"Друзьям",
        "statusName":"expert(29.09 for friends)",
        "type":"special"
    },
    {
        "fundId":407497,
        "fundName":"Спонсорам",
        "statusName":"examplerformance",
        "type":"special"
    },
    {
        "fundId":407497,
        "fundName":"Спонсорам",
        "statusName":"45",
        "type":"special"
    },
    {
        "fundId":407498,
        "fundName":"Друзьям",
        "statusName":"разное",
        "type":"special"
    },
    {
        "fundId":407497,
        "fundName":"Спонсорам",
        "statusName":"GPX-20186-0",
        "type":"special"
    },
    {
        "fundId":407498,
        "fundName":"Друзьям",
        "statusName":"GPX-20186",
        "type":"special"
    },
    {
        "fundId":407497,
        "fundName":"Спонсорам",
        "statusName":"asdfasdf",
        "type":"special"
    },
    {
        "fundId":407497,
        "fundName":"Спонсорам",
        "statusName":"nazvanie",
        "type":"special"
    },
    {
        "fundId":407498,
        "fundName":"Друзьям",
        "statusName":"спец прод 19080",
        "type":"special"
    },
    {
        "fundId":407498,
        "fundName":"Друзьям",
        "statusName":"new test 2",
        "type":"special"
    },
    {
        "fundId":407497,
        "fundName":"Спонсорам",
        "statusName":"new test",
        "type":"special"
    },
    {
        "fundId":407496,
        "fundName":"Поклонникам",
        "statusName":"2786",
        "type":"special"
    },
    {
        "fundId":407498,
        "fundName":"Друзьям",
        "statusName":"5",
        "type":"special"
    },
    {
        "fundId":407498,
        "fundName":"Друзьям",
        "statusName":"test 12322",
        "type":"special"
    },
    {
        "fundId":407497,
        "fundName":"Спонсорам",
        "statusName":"300",
        "type":"special"
    },
    {
        "fundId":407497,
        "fundName":"Спонсорам",
        "statusName":"2",
        "type":"special"
    },
    {
        "fundId":407496,
        "fundName":"Поклонникам",
        "statusName":"2",
        "type":"special"
    },
    {
        "fundId":407496,
        "fundName":"Поклонникам",
        "statusName":"1",
        "type":"special"
    },
    {
        "fundId":407497,
        "fundName":"Спонсорам",
        "statusName":"Не очень интересный фонд",
        "type":"special"
    },
    {
        "fundId":407496,
        "fundName":"Поклонникам",
        "statusName":"КОТ В САПОГАХ",
        "type":"special"
    },
    {
        "fundId":407496,
        "fundName":"Поклонникам",
        "statusName":"300",
        "type":"special"
    },
    {
        "fundId":407498,
        "fundName":"Друзьям",
        "statusName":"300",
        "type":"special"
    }
]